language: node_js

node_js:
  - '6'
  - '5'
  - '4'

before_install:
- rvm install 2.2.3
- curl -o- -L https://yarnpkg.com/install.sh | bash

before_script:
  # install dependencies
  # travis runs `yarn install` when yarn.lock exists

  # install ruby dependencies
  - gem install bundler -v 1.17.3
  - bundle install
